import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FlagsProvider from "../components/flags-provider";
import { getFlags } from "../lib/queries";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const flags = await getFlags();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <FlagsProvider flags={flags}>{children}</FlagsProvider>
      </body>
    </html>
  );
}
