// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetDocsData, GetDocsErrors, PostViewData, PostViewErrors, PostVisitorData, PostVisitorErrors } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postView = <ThrowOnError extends boolean = false>(options?: Options<PostViewData, ThrowOnError>) => (options?.client ?? client).post<unknown, PostViewErrors, ThrowOnError>({
    url: '/view',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const postVisitor = <ThrowOnError extends boolean = false>(options?: Options<PostVisitorData, ThrowOnError>) => (options?.client ?? client).post<unknown, PostVisitorErrors, ThrowOnError>({
    url: '/visitor',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const getDocs = <ThrowOnError extends boolean = false>(options?: Options<GetDocsData, ThrowOnError>) => (options?.client ?? client).get<unknown, GetDocsErrors, ThrowOnError>({ url: '/docs', ...options });
