// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type PostViewData = {
    body?: {
        vid: string;
        sid: string;
        ts: number;
        p: string;
    };
    path?: never;
    query?: never;
    url: '/view';
};

export type PostViewErrors = {
    /**
     * Bad Request. Usually due to missing parameters, or invalid parameters.
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized. Due to missing or invalid authentication.
     */
    401: {
        message: string;
    };
    /**
     * Forbidden. You do not have permission to access this resource or to perform this action.
     */
    403: {
        message?: string;
    };
    /**
     * Not Found. The requested resource was not found.
     */
    404: {
        message?: string;
    };
    /**
     * Too Many Requests. You have exceeded the rate limit. Try again later.
     */
    429: {
        message?: string;
    };
    /**
     * Internal Server Error. This is a problem with the server that you cannot fix.
     */
    500: {
        message?: string;
    };
};

export type PostViewError = PostViewErrors[keyof PostViewErrors];

export type PostVisitorData = {
    body?: {
        vid: string;
        sid: string;
        ts: number;
        p: string;
        ua: string;
        ip: string;
        ref: string;
        loc: string;
        lng: string;
        tz: string;
        dev: string;
        os: string;
    };
    path?: never;
    query?: never;
    url: '/visitor';
};

export type PostVisitorErrors = {
    /**
     * Bad Request. Usually due to missing parameters, or invalid parameters.
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized. Due to missing or invalid authentication.
     */
    401: {
        message: string;
    };
    /**
     * Forbidden. You do not have permission to access this resource or to perform this action.
     */
    403: {
        message?: string;
    };
    /**
     * Not Found. The requested resource was not found.
     */
    404: {
        message?: string;
    };
    /**
     * Too Many Requests. You have exceeded the rate limit. Try again later.
     */
    429: {
        message?: string;
    };
    /**
     * Internal Server Error. This is a problem with the server that you cannot fix.
     */
    500: {
        message?: string;
    };
};

export type PostVisitorError = PostVisitorErrors[keyof PostVisitorErrors];

export type GetDocsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docs';
};

export type GetDocsErrors = {
    /**
     * Bad Request. Usually due to missing parameters, or invalid parameters.
     */
    400: {
        message: string;
    };
    /**
     * Unauthorized. Due to missing or invalid authentication.
     */
    401: {
        message: string;
    };
    /**
     * Forbidden. You do not have permission to access this resource or to perform this action.
     */
    403: {
        message?: string;
    };
    /**
     * Not Found. The requested resource was not found.
     */
    404: {
        message?: string;
    };
    /**
     * Too Many Requests. You have exceeded the rate limit. Try again later.
     */
    429: {
        message?: string;
    };
    /**
     * Internal Server Error. This is a problem with the server that you cannot fix.
     */
    500: {
        message?: string;
    };
};

export type GetDocsError = GetDocsErrors[keyof GetDocsErrors];
